# Auto-generated translatable strings for biglinux-browser-selector
# This file is generated by generate_strings.py

from __future__ import annotations


def _(message: str) -> str:
    """Mark a string as translatable."""
    return message


STRINGS = {
    "page_title": _("Choose your default browser"),
    "page_subtitle": _("Select and install the web browser of your choice."),
    "installing": _("Installing"),
    "still_working": _("Still working…"),
    "setting_default": _("Setting %s as default…"),
    "set_as_default": _("%s set as default"),
    "changing_default_browser": _("Changing default browser"),
    "installed": _("installed"),
    "not_installed": _("not installed"),
    "default_browser": _("default browser"),
    "busy": _("busy"),
}
