# -*- coding: utf-8 -*-
#
# DO NOT EDIT THIS FILE MANUALLY.
#
# This file is automatically generated by the 'generate_strings.py' script
# from the content of a YAML file. It is used by gettext to extract
# translatable strings from data files.
#
import gettext
_ = gettext.gettext

# --- Strings from data file ---
_('Brave')
_('Choose your default browser')
_('Chrome')
_('Chromium')
_('Edge')
_('Falkon')
_('Firefox')
_('Librewolf')
_('Opera')
_('Set your default browser.')
_('Vivaldi')
_('Zen Browser')
